;;;; package.lisp

(pushnew :capstone *features*)

(defpackage #:capstone-ffi)
(defpackage #:capstone-ffi.accessors)
(defpackage #:capstone-ffi.functions)

(defpackage #:capstone
  (:use
   #:cl
   #:autowrap.minimal
   #:plus-c
   #:capstone-ffi.accessors
   #:capstone-ffi.functions)
  (:nicknames #:cs)
  (:import-from
   #:alexandria
   #:with-gensyms
   #:once-only)
  (:export
   #:branch-displacement-operand-displacement
   #:branch-displacement-operand-displacement-size
   #:close-handle
   #:capstone-error
   #:capstone-rc-error
   #:condition-register-operand-condition
   #:condition-register-operand-register
   #:constant-operand-value
   #:direct-operand-address
   #:do-disassembled-instructions
   #:do-instruction-operands
   #:encoding-displacement-offset
   #:encoding-displacement-size
   #:encoding-immediate-offset
   #:encoding-immediate-size
   #:encoding-modrm-offset
   #:extended-operand-address
   #:extended-operand-indirect-address-p
   #:instruction-address
   #:instruction-address-size
   #:instruction-avx-condition-code
   #:instruction-avx-rounding-mode
   #:instruction-avx-sae-p
   #:instruction-branch-code
   #:instruction-branch-hint
   #:instruction-bytes
   #:instruction-condition-code
   #:instruction-condition-code
   #:instruction-condition-register
   #:instruction-condition-zero
   #:instruction-cps-flag
   #:instruction-cps-mode
   #:instruction-displacement
   #:instruction-eflags-updated
   #:instruction-encoding
   #:instruction-fee
   #:instruction-flags
   #:instruction-fpu-flags-updated
   #:instruction-funit-crosspath
   #:instruction-funit-side
   #:instruction-funit-unit
   #:instruction-groups
   #:instruction-hint
   #:instruction-id
   #:instruction-memory-barrier
   #:instruction-mnemonic
   #:instruction-modrm
   #:instruction-number-of-items-popped
   #:instruction-number-of-items-pushed
   #:instruction-opcode
   #:instruction-operand-size
   #:instruction-operand-size-type
   #:instruction-operand-string
   #:instruction-operands
   #:instruction-parallel
   #:instruction-prefix
   #:instruction-registers-read
   #:instruction-registers-written
   #:instruction-rex
   #:instruction-sib
   #:instruction-sib-base-register
   #:instruction-sib-index-register
   #:instruction-sib-scale
   #:instruction-size
   #:instruction-sse-condition-code
   #:instruction-updates-cr0-p
   #:instruction-updates-flags-p
   #:instruction-usermode-p
   #:instruction-vector-data
   #:instruction-vector-size
   #:instruction-writeback-p
   #:instruction-xop-condition-code
   #:memory-operand-base-register
   #:memory-operand-bitfield-p
   #:memory-operand-direction
   #:memory-operand-displacement
   #:memory-operand-displacement-type
   #:memory-operand-flags
   #:memory-operand-increment/decrement
   #:memory-operand-index-register
   #:memory-operand-index-size
   #:memory-operand-indirect-base-register
   #:memory-operand-indirect-displacement
   #:memory-operand-length
   #:memory-operand-lshift
   #:memory-operand-modify
   #:memory-operand-offset
   #:memory-operand-offset-address
   #:memory-operand-offset-bits
   #:memory-operand-other-displacement
   #:memory-operand-scale
   #:memory-operand-scaled
   #:memory-operand-segment-register
   #:memory-operand-unit
   #:memory-operand-width
   #:open-handle
   #:operand-access
   #:operand-addressing-mode
   #:operand-avx-broadcast
   #:operand-avx-zero-opmask-p
   #:operand-barrier
   #:operand-count
   #:operand-double-value
   #:operand-extender
   #:operand-float-value
   #:operand-float-value
   #:operand-immediate-value
   #:operand-neon-lane
   #:operand-prefetch
   #:operand-pstate
   #:operand-register
   #:operand-register-bits
   #:operand-register-pair
   #:operand-setend
   #:operand-shift-type
   #:operand-shift-value
   #:operand-size
   #:operand-subtracted-p
   #:operand-sys-op
   #:operand-type
   #:operand-vector-arrangement-specifier
   #:operand-vector-element-size-specifier
   #:operand-vector-index
   #:relative-operand-address
   #:relative-operand-address-offset
   #:set-option
   #:version
   #:with-open-handle))
